
export default new Map([
["src/content/blog/advanced-css-variables-tips.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fadvanced-css-variables-tips.mdx&astroContentModuleFlag=true")],
["src/content/blog/deploying-a-static-website-with-a-custom-domain-on-github.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fdeploying-a-static-website-with-a-custom-domain-on-github.mdx&astroContentModuleFlag=true")],
["src/content/blog/dev-tools-tips-to-boost-your-web-development.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fdev-tools-tips-to-boost-your-web-development.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-handle-a-hotfix-using-git-fork.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-handle-a-hotfix-using-git-fork.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-target-specific-cells-in-css-grid-css-tip.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-target-specific-cells-in-css-grid-css-tip.mdx&astroContentModuleFlag=true")],
["src/content/blog/my-developer-workspace-tools-extensions-and-setup.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fmy-developer-workspace-tools-extensions-and-setup.mdx&astroContentModuleFlag=true")],
["src/content/blog/why-rebase-instead-of-merge-step-by-step-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fwhy-rebase-instead-of-merge-step-by-step-guide.mdx&astroContentModuleFlag=true")],
["src/content/authors/default.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fauthors%2Fdefault.mdx&astroContentModuleFlag=true")],
["src/content/tags/css.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ftags%2Fcss.mdx&astroContentModuleFlag=true")],
["src/content/tags/default.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ftags%2Fdefault.mdx&astroContentModuleFlag=true")],
["src/content/tags/git.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ftags%2Fgit.mdx&astroContentModuleFlag=true")],
["src/content/tags/tips.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ftags%2Ftips.mdx&astroContentModuleFlag=true")]]);
		