// Automatically generated by astro-icon
// 204b964886f6872ffa1ef664e0c00c24dababac6c170bc1a788d1e6ee63f63b0

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-down"
		| "arrow-top-right"
		| "click-to-copy"
		| "cursor-top-right"
		| "e-commerce"
		| "logo"
		| "motion"
		| "play"
		| "playground-text"
		| "refactoring"
		| "responsive"
		| "seo";
}