// Automatically generated by astro-icon
// 892b065c17df1d2e58bde5bd5bd743f2bbf0e8266205dedac7f078b83d388e05

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-down"
		| "arrow-right"
		| "arrow-top-right"
		| "click-to-copy"
		| "copy"
		| "cursor-top-right"
		| "drag-cursor"
		| "e-commerce"
		| "facebook"
		| "linkedin"
		| "logo"
		| "motion"
		| "pause"
		| "picture-in-picture"
		| "play"
		| "playground-text"
		| "refactoring"
		| "responsive"
		| "right-key"
		| "seo"
		| "x";
}