// Automatically generated by astro-icon
// 02d370c0b486d7ac2e54a65071aedd4a5889877be40f68cf0c6d97c862233ba3

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-down"
		| "arrow-right"
		| "arrow-top-right"
		| "click-to-copy"
		| "cursor-top-right"
		| "e-commerce"
		| "logo"
		| "motion"
		| "play"
		| "playground-text"
		| "refactoring"
		| "responsive"
		| "right-key"
		| "seo";
}